import sys
import pathlib
import os
import argparse
import subprocess
import shutil
import tempfile

def format_val(val):
    """
    Abbreviate numbers using 'k' for thousands and 'm' for millions.
    0 remains '0'.
    """
    if val == 0:
        return "0"
    if val % 1000000 == 0:
        return f"{val // 1000000}m"
    elif val % 1000 == 0:
        return f"{val // 1000}k"
    return str(val)

def int_or_abbrev(val_str):
    val_str = str(val_str).strip().lower()
    if val_str.endswith('k'):
        return int(float(val_str[:-1]) * 1000)
    elif val_str.endswith('m'):
        return int(float(val_str[:-1]) * 1000000)
    return int(val_str)

def parse_arguments():
    parser = argparse.ArgumentParser(
        description="Caster: Compute D* statistic on a genomic range."
    )
    
    # Input FASTA file
    parser.add_argument(
        "fasta_file",
        type=pathlib.Path,
        help="Input FASTA file path"
    )
    
    # Left and Right indices
    parser.add_argument(
        "-l",
        dest="left",
        type=int_or_abbrev,
        required=True,
        help="Left index of range (0-indexed, inclusive)"
    )
    parser.add_argument(
        "-r",
        dest="right",
        type=int_or_abbrev,
        required=True,
        help="Right index of range (0-indexed, exclusive)"
    )
    
    # Dstar parameters
    parser.add_argument(
        "-w",
        dest="window_size",
        type=int_or_abbrev,
        default=10000,
        help="Window size (default: 10000)"
    )
    parser.add_argument(
        "-n",
        dest="normalize",
        action="store_true",
        help="Apply min-max normalization to D* scores"
    )
    return parser.parse_args()

def main():
    args = parse_arguments()
    # Inject defaults for removed CLI flags
    args.step_size = args.window_size
    
    # Auto-detect mapping file in same directory as fasta_file
    args.mapping = None
    default_map = args.fasta_file.parent / f"{args.fasta_file.stem}_mapping.tsv"
    if default_map.exists():
        args.mapping = default_map
    else:
        fallback_map = args.fasta_file.parent / "ape_mapping.tsv"
        if fallback_map.exists():
            args.mapping = fallback_map
    
    # 1. Validation
    if not args.fasta_file.exists():
        sys.exit(f"Error: FASTA file not found at '{args.fasta_file}'")
    if args.left < 0:
        sys.exit(f"Error: Left index must be >= 0, got {args.left}")
    if args.right <= args.left:
        sys.exit(f"Error: Right index must be greater than left index, got left={args.left}, right={args.right}")
        
    temp_dir = tempfile.mkdtemp()
    
    try:
        # 2. Locate dstar binary
        # Script is in phlag/caster.py, repo root is one level up
        repo_root = pathlib.Path(__file__).parent.parent.resolve()
        binary_name = "dstar.exe" if sys.platform == "win32" else "dstar"
        binary_path = repo_root / "caster" / "data" / "bin" / binary_name
            
        if not binary_path.exists():
            sys.exit(f"Error: Could not locate compiled 'dstar' binary at '{binary_path}'")
            
        # 3. Run dstar binary on original fasta file directly (no splicing)
        print(f"Running D* calculation on original file '{args.fasta_file}' with window={args.window_size}, step={args.step_size}...")
        cmd = [str(binary_path), str(args.fasta_file.resolve())]
        if args.mapping:
            if not args.mapping.exists():
                sys.exit(f"Error: Mapping file not found at '{args.mapping}'")
            cmd.append(str(args.mapping.resolve()))
        else:
            cmd.append("-")
            
        cmd.extend(["-w", str(args.window_size), "-s", str(args.step_size)])
        if args.normalize:
            cmd.append("-n")
            
        try:
            result = subprocess.run(cmd, cwd=temp_dir, capture_output=True, text=True, check=True)
        except subprocess.CalledProcessError as e:
            sys.exit(f"Error running 'dstar' binary:\nCommand: {e.cmd}\nExit Code: {e.returncode}\nStdout: {e.stdout}\nStderr: {e.stderr}")
            
        # 4. Read generated TSV file and slice rows by range [left, right)
        norm_suffix = "_n" if args.normalize else ""
        generated_tsv = pathlib.Path(temp_dir) / f"{args.fasta_file.stem}_w{args.window_size}_s{args.step_size}{norm_suffix}.tsv"
        
        if not generated_tsv.exists():
            sys.exit(f"Error: D* output TSV file was not generated by the binary. Stderr: {result.stderr}")
            
        output_lines = []
        with open(generated_tsv, "r") as f:
            # Read header
            header = f.readline()
            output_lines.append(header)
            
            # Filter rows within range [left, right)
            for line in f:
                if not line.strip():
                    continue
                parts = line.strip().split("\t")
                pos_val = int(parts[0])
                if args.left <= pos_val < args.right:
                    output_lines.append("\t".join(parts) + "\n")
                    
        # 5. Write final TSV file to current directory
        # Output filename should not have C, and includes left and right indices (formatted)
        clean_stem = args.fasta_file.stem.replace("C", "")
        left_str = format_val(args.left)
        right_str = format_val(args.right)
        window_str = format_val(args.window_size)
        step_str = format_val(args.step_size)
        
        final_output_name = f"{clean_stem}_{left_str}_{right_str}_w{window_str}_s{step_str}{norm_suffix}.tsv"
        final_output_path = repo_root / "caster" / "data" / final_output_name
        
        with open(final_output_path, "w") as f:
            f.writelines(output_lines)
        print(f"Success: TSV output file generated at: {final_output_path}")
        print(result.stdout)
        
        pass
        
    finally:
        shutil.rmtree(temp_dir)

if __name__ == "__main__":
    main()
