# Run AFTER bench/pair_jobs.txt finishes -- resummarizes each base's pair
# variant from the reports/scores already written directly by phlagster.
benchmark --create store/phlag/gaussian/w50k_s1k/pair -w 50k -s 1k --pair --skip caster,phlag;
benchmark --create store/phlag/gaussian/w50k_s40k/pair -w 50k -s 40k --pair --skip caster,phlag;
benchmark --create store/phlag/gaussian/w100k_s1k/pair -w 100k -s 1k --pair --skip caster,phlag;
benchmark --create store/phlag/gaussian/w100k_s80k/pair -w 100k -s 80k --pair --skip caster,phlag;
benchmark --create store/phlag/gaussian/w250k_s1k/pair -w 250k -s 1k --pair --skip caster,phlag;
benchmark --create store/phlag/gaussian/w250k_s200k/pair -w 250k -s 200k --pair --skip caster,phlag;
benchmark --create store/phlag/gaussian/w500k_s1k/pair -w 500k -s 1k --pair --skip caster,phlag;
benchmark --create store/phlag/gaussian/w500k_s400k/pair -w 500k -s 400k --pair --skip caster,phlag;
benchmark --create store/phlag/gaussian/w50k_s50k/pair -w 50k -s 50k --pair --skip caster,phlag;
benchmark --create store/phlag/gaussian/w100k_s100k/pair -w 100k -s 100k --pair --skip caster,phlag;
benchmark --create store/phlag/gaussian/w250k_s250k/pair -w 250k -s 250k --pair --skip caster,phlag;
benchmark --create store/phlag/gaussian/w500k_s500k/pair -w 500k -s 500k --pair --skip caster,phlag;
benchmark --create store/phlag/gaussian/w10k_s1k/pair -w 10k -s 1k --pair --skip caster,phlag;
benchmark --create store/phlag/gaussian/w10k_s10k/pair -w 10k -s 10k --pair --skip caster,phlag;
benchmark --create store/phlag/gaussian/w1m_s1k/pair -w 1m -s 1k --pair --skip caster,phlag;
benchmark --create store/phlag/gaussian/w1m_s800k/pair -w 1m -s 800k --pair --skip caster,phlag;
benchmark --create store/phlag/gaussian/w1m_s1m/pair -w 1m -s 1m --pair --skip caster,phlag;
